apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "name" . }}
    role: grid
    chart: {{ template "chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: NodePort
  ports:
  - name: server
    port: 7272
    targetPort: 7272
  selector:
    app: {{ template "name" . }}
    release: "{{ .Release.Name }}"
